### REGISTER USER
POST http://localhost:4400/user/register
Content-Type: application/json

{
    "profile_image_link":"",
    "name":"Robinson Ngecu",
    "email": "devngecu@gmail.com",
    "password": "3W!W.:srzc4r^!P",
    "username":"devngecu",
    "phone_no":"0707583092",
    "created_at":"Now"
}


## LOGIN USER
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "email": "devngecu@gmail.com",
    "password": "3W!W.:srzc4r^!P"
}


## TOGGLE FOLLOW USER
POST http://localhost:4400/user/toggleFollowUser
Content-Type: application/json

{
   "following_user_id":"sdfdfsdf", 
   "followed_user_id":"dsadasd",
   "created_at":"dasdasdsd"
}

## GET FOLLOWERS
POST http://localhost:4400/user/getFollowers
Content-Type: application/json

{
   "followed_user_id":"dsadasd",
}

## GET FOLLOWINGS
POST http://localhost:4400/user/getFollowings
Content-Type: application/json

{
   "following_user_id":"dsadasd",
}


## following Posts
###
GET http://localhost:4400/post/64b14daa-ad76-49d8-a5bd-ae298e15dde3

Content-Type: application/json



## CREATE POST

POST http://localhost:4400/post/
Content-Type: application/json

{
    "created_by_user_id":"weaesdasdsd",
    "caption":"This is my first caption",
    "postType":"status",
    "created_at":"now"
}

