### REGISTER USER
POST http://localhost:4400/user/register
Content-Type: application/json

{
    "profileImage":"https://res.cloudinary.com/dqquyjsap/image/upload/v1702401134/x7uybc4bmysvedyzgbvs.jpg",
    "name":"Christine Nduta",
    "email": "ngecu16@gmail.com",
    "password": "3W!W.:srzc4r^!P",
    "username":"christine",
    "phone_no":"0707583091",
    "created_at":"2023-12-12T17:12:18"
}


## LOGIN USER
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "email": "devngecu@gmail.com",
    "password": "3W!W.:srzc4r^!P"
}


## TOGGLE FOLLOW USER
###
POST http://localhost:4400/user/toggleFollowUser
Content-Type: application/json

{
   "following_user_id":"b73120f8-6670-4991-9045-85db8962aa56", 
   "followed_user_id":"64b14daa-ad76-49d8-a5bd-ae298e15dde3",
    "created_at":"2023-12-12T17:12:18"
}

## GET FOLLOWERS
###
POST http://localhost:4400/user/getFollowers
Content-Type: application/json

{
   "followed_user_id":"64b14daa-ad76-49d8-a5bd-ae298e15dde3"
}

## GET FOLLOWINGS
POST http://localhost:4400/user/getFollowings
Content-Type: application/json

{
   "following_user_id":"dsadasd",
}

## GET FOLLOWERS
###
POST http://localhost:4400/user/reset-password
Content-Type: application/json

{
   "Email":"ngecu16@gmail.com"
}

## following Posts
###
GET http://localhost:4400/post/64b14daa-ad76-49d8-a5bd-ae298e15dde3

Content-Type: application/json



## CREATE POST

POST http://localhost:4400/post/
Content-Type: application/json

{
    "created_by_user_id":"weaesdasdsd",
    "caption":"This is my first caption",
    "postType":"status",
    "created_at":"now"
}

