## following Posts
###
GET http://localhost:4400/post/64b14daa-ad76-49d8-a5bd-ae298e15dde3

Content-Type: application/json



## CREATE POST

POST http://localhost:4400/post/
Content-Type: application/json

{
    "created_by_user_id":"weaesdasdsd",
    "caption":"This is my first caption",
    "postType":"status",
    "created_at":"now"
}

###
POST http://localhost:4400/post/comment
Content-Type: application/json

{
    "post_id":"696f552d-1720-4dc9-9d9c-3f81569c0498",
    "created_by_user_id":"64b14daa-ad76-49d8-a5bd-ae298e15dde3",
    "comment":"This is my first caption",
    "created_at":"now"
}


