################################################################################################################################

### REGISTER USER
POST http://localhost:4400/user/register
Content-Type: application/json

{
    "profileImage":"https://res.cloudinary.com/dqquyjsap/image/upload/v1702401134/x7uybc4bmysvedyzgbvs.jpg",
    "fullName":"Caleb ",
    "email": "caleb@gmail.com",
    "password": "12345678",
    "username":"caleb",
    "phone_no":"0791885527"
}


### LOGIN USER
POST http://localhost:4400/user/login
Content-Type: application/json

{
    "email":  "caleb@gmail.com",
    "password": "12345678"
}

###
GET http://localhost:4400/user/check_user_details
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbXBsb3llZV9pZCI6ImRmZTI4ZDA3LTJhM2EtNDdmNC05MDBjLWNmMzc2ZTE5OThkYiIsIm5hbWUiOiJEYW5pZWwgS2l0aGVrYSIsImVtYWlsIjoiZGFuQHlvcG1haWwuY29tIiwicm9sZSI6ImVtcGxveWVlIiwiaXNEZWxldGVkIjp0cnVlLCJpYXQiOjE3MDA0NjQwOTIsImV4cCI6MTcwMDU1MDQ5Mn0.q3gT-P3dN8R3pilhSYbJD576jMg1KxN6xKgNNNVMCps


### TOGGLE SOFT DELETE USER
PUT http://localhost:4400/user/toggleSoftDeleteUser/21960f9e-1e17-4bbb-aad3-732792f75372
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjY4ZGUxMmEtMTBlMi00MGU1LTk1M2ItOTU5Zjk0ZGM1YTdkIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9jZG4wLmljb25maW5kZXIuY29tL2RhdGEvaWNvbnMvdWktYW5kLXV4LWJhc2ljLW91dGxpbmUvNjQvdXNlcl91aV91eF9nZW5lcmFsLTUxMi5wbmciLCJmdWxsTmFtZSI6InJlYmVjY2EiLCJlbWFpbCI6IndhbmppcnViZWNreS5yd0BnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImJlY2t5c2hlZSIsInBob25lX25vIjoiMDc5MTg4NTUyNyIsImFjdGl2ZSI6MSwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMThUMTM6MjM6MjUuOTkzWiIsImlhdCI6MTcwMjk5MDg4OCwiZXhwIjoxNzAzMDc3Mjg4fQ.J3pvDwoyuKqqcHiL2BDroYyh-kHc4TEQfOndLlO8aAY
### UPDATE USER PROFILE
PUT http://localhost:4400/user/5c74fdc6-d58f-4e47-8132-8ef1b20e9edb/profile
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiMTRkYWEtYWQ3Ni00OWQ4LWE1YmQtYWUyOThlMTVkZGUzIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZHFxdXlqc2FwL2ltYWdlL3VwbG9hZC92MTcwMjQwMTEzNC94N3V5YmM0Ym15c3ZlZHl6Z2J2cy5qcGciLCJmdWxsTmFtZSI6IlJvYmluIiwiZW1haWwiOiJkZXZuZ2VjdUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRldm5nZWN1IiwicGhvbmVfbm8iOiIwNzA3NTgzMDkyIiwiYWN0aXZlIjoxLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0xMlQxNzoxMjoxOC4iLCJpYXQiOjE3MDI1NjMzMjUsImV4cCI6MTcwMjY0OTcyNX0.J2o6hYFQD0raldxMj6LzFJ8lJHAQ92WR3tZ2-c0eS-E

{
    "profileImage":"https://res.cloudinary.com/dqquyjsap/image/upload/v1702401134/x7uybc4bmysvedyzgbvs.jpg",
    "fullName":"Sandra Mwihaki",
    "username":"sandrA",
    "phone_no":"0791885527"

}


### GET ALL USERS
GET http://localhost:4400/user
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiMTRkYWEtYWQ3Ni00OWQ4LWE1YmQtYWUyOThlMTVkZGUzIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZHFxdXlqc2FwL2ltYWdlL3VwbG9hZC92MTcwMjQwMTEzNC94N3V5YmM0Ym15c3ZlZHl6Z2J2cy5qcGciLCJmdWxsTmFtZSI6IlJvYmluIiwiZW1haWwiOiJkZXZuZ2VjdUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRldm5nZWN1IiwicGhvbmVfbm8iOiIwNzA3NTgzMDkyIiwiYWN0aXZlIjoxLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0xMlQxNzoxMjoxOC4iLCJpYXQiOjE3MDI1NjMzMjUsImV4cCI6MTcwMjY0OTcyNX0.J2o6hYFQD0raldxMj6LzFJ8lJHAQ92WR3tZ2-c0eS-E

###
GET http://localhost:4400/user/getFollowSuggestions/34a5bb26-e5b6-45a1-9041-39054e94707c
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiMTRkYWEtYWQ3Ni00OWQ4LWE1YmQtYWUyOThlMTVkZGUzIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZHFxdXlqc2FwL2ltYWdlL3VwbG9hZC92MTcwMjQwMTEzNC94N3V5YmM0Ym15c3ZlZHl6Z2J2cy5qcGciLCJmdWxsTmFtZSI6IlJvYmluIiwiZW1haWwiOiJkZXZuZ2VjdUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRldm5nZWN1IiwicGhvbmVfbm8iOiIwNzA3NTgzMDkyIiwiYWN0aXZlIjoxLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0xMlQxNzoxMjoxOC4iLCJpYXQiOjE3MDI1NjMzMjUsImV4cCI6MTcwMjY0OTcyNX0.J2o6hYFQD0raldxMj6LzFJ8lJHAQ92WR3tZ2-c0eS-E



### TOGGLE FOLLOW USER
POST http://localhost:4400/user/toggleFollowUser
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMzRhNWJiMjYtZTViNi00NWExLTkwNDEtMzkwNTRlOTQ3MDdjIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZHFxdXlqc2FwL2ltYWdlL3VwbG9hZC92MTcwMjcyNDc4My9nc2ZycDltdjh1Y3Bqb2pld3Bkei5qcGciLCJmdWxsTmFtZSI6IlJvYmluc29uIE5nZWN1IiwiZW1haWwiOiJkZXZuZ2VjdUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRldm5nZWN1IiwicGhvbmVfbm8iOiIwNzA3NTgzMDkyIiwiYWN0aXZlIjoxLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0xNlQxMTowNjoyMS4iLCJpYXQiOjE3MDI3OTMwMTcsImV4cCI6MTcwMjg3OTQxN30.Huf7tI80qXdIj_FKVQEW-rIV3BOL2ItMsAfHgTCqxvg

{
   "following_user_id":"d68e4e4e-9419-4b52-8f92-717881786a00", 
   "followed_user_id":"47027207-f0fa-4b5d-977b-ec9304fd292f"
}

## GET FOLLOWERS
###
GET http://localhost:4400/user/getFollowers/64b14daa-ad76-49d8-a5bd-ae298e15dde3
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZjY4ZGUxMmEtMTBlMi00MGU1LTk1M2ItOTU5Zjk0ZGM1YTdkIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9hdmF0YXJzLmdpdGh1YnVzZXJjb250ZW50LmNvbS91Lzk3ODc1NTEwP3Y9NCIsImZ1bGxOYW1lIjoicmViZWNjYSIsImVtYWlsIjoid2FuamlydWJlY2t5LnJ3QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiYmVja3lzaGVlIiwicGhvbmVfbm8iOiIwNzkxODg1NTI3IiwiYWN0aXZlIjoxLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0xOFQxMzoyMzoyNS45OTNaIiwiaWF0IjoxNzAzMDQ0MDA2LCJleHAiOjE3MDMxMzA0MDZ9.g5nRSUNGpvc8NoS3PVM1KN_uMID1QQ6gT3RGfuLxrqE

### GET FOLLOWINGS
GET http://localhost:4400/user/getFollowings/b73120f8-6670-4991-9045-85db8962aa56
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjRiMTRkYWEtYWQ3Ni00OWQ4LWE1YmQtYWUyOThlMTVkZGUzIiwicHJvZmlsZUltYWdlIjoiaHR0cHM6Ly9yZXMuY2xvdWRpbmFyeS5jb20vZHFxdXlqc2FwL2ltYWdlL3VwbG9hZC92MTcwMjQwMTEzNC94N3V5YmM0Ym15c3ZlZHl6Z2J2cy5qcGciLCJmdWxsTmFtZSI6IlJvYmluIiwiZW1haWwiOiJkZXZuZ2VjdUBnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImRldm5nZWN1IiwicGhvbmVfbm8iOiIwNzA3NTgzMDkyIiwiYWN0aXZlIjoxLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0xMlQxNzoxMjoxOC4iLCJpYXQiOjE3MDI1NjMzMjUsImV4cCI6MTcwMjY0OTcyNX0.J2o6hYFQD0raldxMj6LzFJ8lJHAQ92WR3tZ2-c0eS-E


### SEND RESET PASSWORD TOKEN LINK
POST http://localhost:4400/user/reset-password
Content-Type: application/json

{
   "Email":"Robinson Ngecu"
}


### SET NEW PASSWORD
POST http://localhost:4400/user/setNewPassword/21960f9e-1e17-4bbb-aad3-732792f75372
Content-Type: application/json

{
   "password":"ngecu16@gmail.com"
}
