###REGISTER USER
POST http://localhost:4500/user/register
Content-Type: application/json

{
    "fullname":"Sandra Mwihaki",
    "username": "SandraMwihaki123",
    "email":"sandramwihaki@gmail.com",
    "password":"12345678"
}

###LOGIN USER
POST http://localhost:4500/user/login
Content-Type: application/json

{
    "email":"gamemy177@gmail.com",
    "password":"12345678"
}

###CHECK USER DETAILS
GET http://localhost:4500/user/checkuserdetails
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI3MTgyMzksImV4cCI6MTcwMjgwNDYzOX0.AygvdQnexPR5Ro46iwrwbKsaU7ZrxuXqdEAJojS5RLY

###GET ALL USERS
GET http://localhost:4500/user/getallusers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMzEwNDI3MCwiZXhwIjoxNzAzMTkwNjcwfQ.PUMfZVCzrtAaum3d3Jv1s6uSTr1l0lRCJeOSRr-tf8c

###getoneuser
POST http://localhost:4500/user/getoneuser
Content-Type: application/json

{
    "email": "gamemy177@gmail.com"
}
###GET USER BY ID
GET http://localhost:4500/user/byId/04947279-d765-4eac-b6f6-96beed409ba9
token:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI4ODM3ODMsImV4cCI6MTcwMjk3MDE4M30.-nI8Fszl456y13VJVG3G-fSRB5E9bbqIYZEgk3DSdg8
Content-Type: application/json

###updateuser
PUT http://localhost:4500/user/updateuser
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjk3NjQ2OCwiZXhwIjoxNzAzMDYyODY4fQ.otDjPcnvkR_lVn10mcKLXvn7IsQSvt2ESjBoomZjBFI
Content-Type: application/json

{
    "userID":"764a7ece-8faa-485a-95ba-01ba11601dd9",
    "fullname": "Ronin Ngecu",
    "profileUrl": "https://cdn.pixabay.com/photo/2023/02/18/04/38/man-7797279_640.jpg",
    "profileCaption": "Pleasure to meet you"
}
###DELETE USER
DELETE http://localhost:4500/user/deleteuser/3b0a993b-be0e-43aa-8af4-e2b5f44d98fa
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiI1ZTRkY2M0NC0xZjE4LTQzMjYtOTkwZS0yZGZhYTdmM2JiZmEiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoibm8taW1hZ2UiLCJwcm9maWxlQ2FwdGlvbiI6Ik5vIENhcHRpb24iLCJpc1dlbGNvbWVkIjp0cnVlLCJpc0RlbGV0ZWQiOmZhbHNlLCJyZXNldFBhc3N3b3JkIjpmYWxzZSwicmVzZXRUb2tlbiI6bnVsbCwiZXhwaXJ5VGltZSI6bnVsbCwiT1RQIjpudWxsLCJjcmVhdGVkX2F0IjoiMjAyMy0xMi0xNVQxMTo0Mjo1MS40MjNaIiwiaWF0IjoxNzAyNjMxNjQ3LCJleHAiOjE3MDI3MTgwNDd9.IFWgLnwNU05bqRh3g9uJ2bJSk4Bq6AT8I1UAANVa7bM

#### FORGOT PASSWORD
POST http://localhost:4500/user/forgot 
Content-Type: application/json

{
    "email":"ngecu16@gmail.com"
}

###RESET PASSWORD
POST http://localhost:4500/user/resetpassword
Content-Type: application/json

{
    "email": "ngecu16@gmail.com",
    "resetToken": "dfe3f7fe-c959-43f2-8a50-ff1f50d37db5",
    "newPassword": "1234567890"
}

###CREATE POST
POST http://localhost:4500/post/create
Content-Type: application/json

{
    "postContent":"Unwrapping joy and spreading cheer - it's the most wonderful time of the year! 🎄✨ #ChristmasMagic #JoyfulMoments",
    "imageUrl":"https://cdn.pixabay.com/photo/2019/02/04/07/36/new-year-3974099_640.jpg",
    "userID":"04947279-d765-4eac-b6f6-96beed409ba9"
}

###GET ALL POSTS
GET http://localhost:4500/post/all 
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjk5MTA2NSwiZXhwIjoxNzAzMDc3NDY1fQ.Ufa78Cjl4r_RzMtYhsE99jpHcCnDKROzMZg2naR79n4

###GET POST BY USERID
GET http://localhost:4500/post/byUserID/ddce142c-a52e-44e9-9dbc-dc44b19877e8
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjg5OTM4NSwiZXhwIjoxNzAyOTg1Nzg1fQ.NAp4qoDECx7Ksx89UgBRMx9axxdD2IoW_QRhchJW0LY

###GET SINGLE POST
GET http://localhost:4500/post/single/aac94e1e-fcb4-48c7-8add-243bda111a40
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjg5OTM4NSwiZXhwIjoxNzAyOTg1Nzg1fQ.NAp4qoDECx7Ksx89UgBRMx9axxdD2IoW_QRhchJW0LY

###UPDATE POST
PUT http://localhost:4500/post/update
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI3MTgyMzksImV4cCI6MTcwMjgwNDYzOX0.AygvdQnexPR5Ro46iwrwbKsaU7ZrxuXqdEAJojS5RLY
Content-Type: application/json

{
    "postID":"da336a69-a734-4568-9b72-0d9f747e1a9b",
    "userID": "04947279-d765-4eac-b6f6-96beed409ba9",
    "postContent": "Wishing you all a cozy and magical Christmas filled with love and laughter! #FestiveCheers #WarmWishes",
    "imageUrl": "https://cdn.pixabay.com/photo/2019/12/06/19/06/gifts-4678018_640.jpg"
}

###DELETE POST
DELETE http://localhost:4500/post/delete/e6cf50ce-8c06-49b7-b5bc-a1aca881c94b
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI4MDQ3NjIsImV4cCI6MTcwMjg5MTE2Mn0.PgDtAMyhpLIik5dFFq8Kkq7FffQ1IjaeMtsOITzsX7Q

###like and unlike post
POST http://localhost:4500/post/likepost
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjk5MTA2NSwiZXhwIjoxNzAzMDc3NDY1fQ.Ufa78Cjl4r_RzMtYhsE99jpHcCnDKROzMZg2naR79n4
Content-Type: application/json

{
   "userID":"04947279-d765-4eac-b6f6-96beed409ba9", 
   "postID":"008e9b77-26c7-4e92-9849-670844af2bf9"
}

###GET ALL LIKES FROM POST
GET http://localhost:4500/post/getlikes/d15f3dcc-0878-42d0-a10b-0a10c6f49b0f
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjk5MTA2NSwiZXhwIjoxNzAzMDc3NDY1fQ.Ufa78Cjl4r_RzMtYhsE99jpHcCnDKROzMZg2naR79n4

###FOLLOW AND UNFOLLOW USERS
POST http://localhost:4500/user/toggleFollowUser
Content-Type: application/json

{
   "following_userID":"33f9de61-d6b8-4d61-b1f4-b8fec2e4052f", 
   "followed_userID":"04947279-d765-4eac-b6f6-96beed409ba9"
}

### GET FOLLOWINGS
GET http://localhost:4500/user/getFollowings/ddce142c-a52e-44e9-9dbc-dc44b19877e8
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI4Mzg2MDAsImV4cCI6MTcwMjkyNTAwMH0.j4E0GOehXNT788YvqCtYIZk8brTyUUsQDlyiZUjedJw

### GET FOLLOWERS
GET http://localhost:4500/user/getFollowers/ddce142c-a52e-44e9-9dbc-dc44b19877e8
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI4Mzg2MDAsImV4cCI6MTcwMjkyNTAwMH0.j4E0GOehXNT788YvqCtYIZk8brTyUUsQDlyiZUjedJw

###CREATE COMMENTS
POST http://localhost:4500/post/createcomment
Content-Type: application/json

{
    "comment":"There's something soothing about the sound of raindrops falling on an umbrella.",
    "postID":"aac94e1e-fcb4-48c7-8add-243bda111a40",
    "userID":"33f9de61-d6b8-4d61-b1f4-b8fec2e4052f"
}

###REPLY TO A COMMENT
POST http://localhost:4500/post/replycomment
Content-Type: application/json

{
    "parentCommentID": "700af1a8-46e2-4189-b5a6-a560bf03e81c",
    "comment":"Raindrops on the umbrella, nature's lullaby, soothing, calming, comforting embrace.",
    "postID":"aac94e1e-fcb4-48c7-8add-243bda111a40",
    "userID":"33f9de61-d6b8-4d61-b1f4-b8fec2e4052f"
}

###GET ALL COMMENTS
GET http://localhost:4500/post/allcomments
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjg5OTM4NSwiZXhwIjoxNzAyOTg1Nzg1fQ.NAp4qoDECx7Ksx89UgBRMx9axxdD2IoW_QRhchJW0LY

###update COMMENT
PUT http://localhost:4500/post/updatecomment
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI3MTgyMzksImV4cCI6MTcwMjgwNDYzOX0.AygvdQnexPR5Ro46iwrwbKsaU7ZrxuXqdEAJojS5RLY
Content-Type: application/json

{
    "postID":"d15f3dcc-0878-42d0-a10b-0a10c6f49b0f",
    "userID": "04947279-d765-4eac-b6f6-96beed409ba9",
    "comment": "Finally Christmas is here!!! Let's celebrate",
    "commentID": "3161c94d-3aee-42e3-8953-94b0395751db"
}

###GET ALL COMMENTS USING POSTID
GET http://localhost:4500/post/getcomments/aac94e1e-fcb4-48c7-8add-243bda111a40
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjg5OTM4NSwiZXhwIjoxNzAyOTg1Nzg1fQ.NAp4qoDECx7Ksx89UgBRMx9axxdD2IoW_QRhchJW0LY


###DELETE COMMENT
DELETE http://localhost:4500/post/deletecomment/cd0e2a88-d1e8-49ca-b355-30d929d450e6
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6dHJ1ZSwiaXNEZWxldGVkIjpmYWxzZSwicmVzZXRQYXNzd29yZCI6ZmFsc2UsInJlc2V0VG9rZW4iOm51bGwsImV4cGlyeVRpbWUiOm51bGwsIk9UUCI6bnVsbCwiY3JlYXRlZF9hdCI6IjIwMjMtMTItMTZUMTA6NTI6NDUuMDY3WiIsImlhdCI6MTcwMjg5OTM4NSwiZXhwIjoxNzAyOTg1Nzg1fQ.NAp4qoDECx7Ksx89UgBRMx9axxdD2IoW_QRhchJW0LY

#  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJkZGNlMTQyYy1hNTJlLTQ0ZTktOWRiYy1kYzQ0YjE5ODc3ZTgiLCJlbWFpbCI6ImdhbWVteTE3N0BnbWFpbC5jb20iLCJmdWxsbmFtZSI6IkRhbmllbCBLaXRoZWthIiwidXNlcm5hbWUiOiJEYW5pZWxLaXRoZWthMTIzIiwicm9sZSI6InVzZXIiLCJwcm9maWxlVXJsIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAyMy8xMS8yMS8wMC8xMy9haS1nZW5lcmF0ZWQtODQwMjEyOV82NDAucG5nIiwicHJvZmlsZUNhcHRpb24iOiJObyBDYXB0aW9uIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsInJlc2V0UGFzc3dvcmQiOmZhbHNlLCJyZXNldFRva2VuIjpudWxsLCJleHBpcnlUaW1lIjpudWxsLCJPVFAiOm51bGwsImNyZWF0ZWRfYXQiOiIyMDIzLTEyLTE2VDEwOjUyOjQ1LjA2N1oiLCJpYXQiOjE3MDI4MDQ3NjIsImV4cCI6MTcwMjg5MTE2Mn0.PgDtAMyhpLIik5dFFq8Kkq7FffQ1IjaeMtsOITzsX7Q
